### ISSUE TITLE
UPM error

### ISSUE THREAD

**Issue by jaraen** [keijiro/PuppetTest#1]
Hi! This random dancer looks really awesome and I was very curious to test it, but I have two errors after importing it in **Unity 2017.3.1f1** for MacOS

I've cloned the repo and inited submodules, just in case, but still I have these two errors:

```
/Users/xxx/Library/Unity/cache/packages/staging-packages.unity.com/com.unity.package-manager-ui@1.5.1/Editor/Sources/Services/Packages/PackageInfo.cs(38,16): error CS0246: The type or namespace name `OriginType' could not be found. Are you missing an assembly reference?


/Users/xxx/Library/Unity/cache/packages/staging-packages.unity.com/com.unity.package-manager-ui@1.5.1/Editor/Sources/Services/Upm/UpmBaseOperation.cs(13,40): error CS0246: The type or namespace name `OriginType' could not be found. Are you missing an assembly reference?

```

any thought?

**Comment by keijiro** [comment]
It seems there is an issue with the package manager. How about removing this line from manifest.json?

https://github.com/keijiro/PuppetTest/blob/master/UnityPackageManager/manifest.json#L8

**Comment by jaraen** [comment]
Thanks a lot! That worked. The project is really funny, thanks for sharing!

**Comment by keijiro** [comment]
Thanks for the verification. Then I'll remove the line.
