### ISSUE TITLE
Having issues setting up dancers: Getting error in the compiler stating it can't find NoiseHelper

### ISSUE THREAD

**Issue by jo-nathanleee** [keijiro/PuppetTest#4]
Here's the error message I'm getting in the compiler. 
I added Klak 1.1.0 through the Unity Package and imported the PuppetTest. I'm a bit new to Unity and Github so let me know if there's anything else I should mention!

Assets\PuppetTest-master\Assets\Puppet\Runtime\Dancer.cs(4,25): error CS0234: The type or namespace name 'NoiseHelper' does not exist in the namespace 'Klak.Math' (are you missing an assembly reference?)

**Comment by keijiro** [comment]
It has dependencies to `jp.keijiro.klak.math`.

https://github.com/keijiro/PuppetTest/blob/master/Packages/manifest.json#L10

**Comment by keijiro** [comment]
I'm closing this issue now. Please reopen it for further problems.
